spring.datasource.url= jdbc:postgresql://localhost:5432/narxozdb
spring.datasource.username= postgres
spring.datasource.password= Butterfly
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update

bezkoder.app.jwtSecret= ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs=86400000

